name: valuify
description: A premium personal finance tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  google_sign_in: ^6.2.2
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Charts
  fl_chart: ^0.65.0
  
  # Image Handling
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  local_auth: ^2.1.8
  
  # PDF & CSV
  pdf: ^3.10.7
  path_provider: ^2.1.1
  csv: ^5.1.1
  open_file: ^3.3.2
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  universal_html: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env

